apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-nonzero-exit-code
  labels:
    is-opni-demo: "true"
spec:
  completions: 10
  parallelism: 10
  template:
    spec:
      containers:
        - name: test
          image: busybox
          command:
          - /bin/false
      restartPolicy: Never